name: "Push Build to Artifactory"
on: [push,workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
   
    steps:
      # This action checks out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # This action sets up the JFrog CLI with the Artifactory URL and access token     
      - uses: jfrog/setup-jfrog-cli@v4
        name: Setup JFrog CLI
        id: setup-cli
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_PROJECT: ${{ vars.JF_PROJECT }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}

      # This command adds a new server configuration to the JFrog CLI   
      - run: |
          export SERVER_ID="jfrog-sca-test"
          jf c add $SERVER_ID --url=${{ secrets.JF_URL }} --access-token=$ACCESS_TOKEN --interactive=false

      - run: |
          jf rt ping
          # Configure NPM  
          jf npmc --repo-deploy=sca-npm --repo-resolve=sca-npm
          # NPM Install
          jf npm install --build-name=sca-npm-build --build-number=1.0.${{github.run_number}}
          # add dependencies 
          jf rt build-add-git sca-npm-build 1.0.${{github.run_number}}
          # collect git 
          jf rt build-collect-env sca-npm-build 1.0.${{github.run_number}}
          # npm publish 
          jf rt npm-publish --build-name=sca-npm-build --build-number=1.0.${{github.run_number}}
          # build publish
          jf rt build-publish sca-npm-build 1.0.${{github.run_number}}
